### ISSUE TITLE
server VM shell provisioner errors

### ISSUE THREAD

**Issue by wdennis** [CumulusNetworks/cldemo-vagrant#1]
Not sure if it's a problem - doesn't seem to affect the operation of the demo, but... in the server[01,02] provisioning I'm getting:

   ==> server01: Running provisioner: shell...
       server01: Running: inline script
   ==> server01: basename:
   ==> server01: missing operand
   ==> server01: Try 'basename --help' for more information.
   ==> server01: basename:
   ==> server01: missing operand
   ==> server01: Try 'basename --help' for more information.
   ==> server01: basename:
   ==> server01: missing operand
   ==> server01: Try 'basename --help' for more information.
   ==> server01: basename:
   ==> server01: missing operand
   ==> server01: Try 'basename --help' for more information.
   ==> server01: basename:
   ==> server01: missing operand
   ==> server01: Try 'basename --help' for more information.
   ==> server01: basename:
   ==> server01: missing operand
   ==> server01: Try 'basename --help' for more information.
   ==> server01: basename:
   ==> server01: missing operand
   ==> server01: Try 'basename --help' for more information.
   ==> server01: basename:
   ==> server01: missing operand
   ==> server01: Try 'basename --help' for more information.

**Comment by ericpulvino** [comment]
Cosmetic; just some output that needs to be hidden.... we've pushed changes to rectify that here --> https://github.com/CumulusNetworks/cldemo-vagrant/commit/aa3a60824daef4d4dccdc27b6e7f3583d6e4fdcb#diff-cd1435d2a13789ced837c1744ee42728
