### ISSUE TITLE
Setup oob-mgmt-switch in DNS on mgmt server

### ISSUE THREAD

**Issue by jaheller** [CumulusNetworks/cldemo-vagrant#11]
Idea is to allow in-band management of the oob-mgmt-switch via Ansible if desired.

Notes for changes I would like to make for this update.
1. Update the topology.dot file and set the MAC for swp1 on oob-mgmt-switch to be A0:00:00:00:00:61 so it is the lowest MAC.
2. Regenerate the Vagrantfiles with topology converter.
3. This should update the wbench_hosts with an entry for the oob-mgmt-server

**Comment by ericpulvino** [comment]
Going to tackle this in the move to the "-c" workflow.

**Comment by ericpulvino** [comment]
A0:00:00:00:00:61 on swp1 will map to 192.168.0.1 per IPAM

**Comment by ericpulvino** [comment]
Done.
