### ISSUE TITLE
Unable to boot oob-mgmt-server in newest version of Vagrantfile

### ISSUE THREAD

**Issue by sutharsan-sivapalan** [CumulusNetworks/cldemo-vagrant#16]
A customer attempted to vagrant up on the latest version and saw the following.  I ran into the same issue when attempting to bring up the machines:

johnm@blowie5:~$ vagrant plugin install vagrant-cumulus
Installing the 'vagrant-cumulus' plugin. This can take a few minutes...
Installed the plugin 'vagrant-cumulus (0.1)'!
johnm@blowie5:~$ git clone https://github.com/cumulusnetworks/cldemo-vagrant
Cloning into 'cldemo-vagrant'...
remote: Counting objects: 699, done.
remote: Total 699 (delta 0), reused 0 (delta 0), pack-reused 699
Receiving objects: 100% (699/699), 1.38 MiB | 751.00 KiB/s, done.
Resolving deltas: 100% (371/371), done.
Checking connectivity... done.
johnm@blowie5:~$ cd cldemo-vagrant

johnm@blowie5:~/cldemo-vagrant$ vagrant up
Bringing machine 'oob-mgmt-server' up with 'virtualbox' provider...
Bringing machine 'oob-mgmt-switch' up with 'virtualbox' provider...
Bringing machine 'exit02' up with 'virtualbox' provider...
Bringing machine 'exit01' up with 'virtualbox' provider...
Bringing machine 'spine02' up with 'virtualbox' provider...
Bringing machine 'spine01' up with 'virtualbox' provider...
Bringing machine 'leaf04' up with 'virtualbox' provider...
Bringing machine 'leaf02' up with 'virtualbox' provider...
Bringing machine 'leaf03' up with 'virtualbox' provider...
Bringing machine 'leaf01' up with 'virtualbox' provider...
Bringing machine 'edge01' up with 'virtualbox' provider...
Bringing machine 'server01' up with 'virtualbox' provider...
Bringing machine 'server03' up with 'virtualbox' provider...
Bringing machine 'server02' up with 'virtualbox' provider...
Bringing machine 'server04' up with 'virtualbox' provider...
Bringing machine 'internet' up with 'virtualbox' provider...
==> oob-mgmt-server: Box 'boxcutter/ubuntu1604' could not be found. Attempting to find and install...
    oob-mgmt-server: Box Provider: virtualbox
    oob-mgmt-server: Box Version: >= 0
==> oob-mgmt-server: Loading metadata for box 'boxcutter/ubuntu1604'
    oob-mgmt-server: URL: https://atlas.hashicorp.com/boxcutter/ubuntu1604
==> oob-mgmt-server: Adding box 'boxcutter/ubuntu1604' (v2.0.23) for provider: virtualbox
    oob-mgmt-server: Downloading: https://atlas.hashicorp.com/boxcutter/boxes/ubuntu1604/versions/2.0.23/providers/virtualbox.box
==> oob-mgmt-server: Successfully added box 'boxcutter/ubuntu1604' (v2.0.23) for 'virtualbox'!
==> oob-mgmt-server: Importing base box 'boxcutter/ubuntu1604'...
==> oob-mgmt-server: Matching MAC address for NAT networking...
==> oob-mgmt-server: Checking if box 'boxcutter/ubuntu1604' is up to date...
==> oob-mgmt-server: Setting the name of the VM: 1_oob-mgmt-server
==> oob-mgmt-server: Clearing any previously set network interfaces...
==> oob-mgmt-server: Preparing network interfaces based on configuration...
    oob-mgmt-server: Adapter 1: nat
    oob-mgmt-server: Adapter 2: intnet
==> oob-mgmt-server: Forwarding ports...
    oob-mgmt-server: 22 (guest) => 2222 (host) (adapter 1)
==> oob-mgmt-server: Running 'pre-boot' VM customizations...
==> oob-mgmt-server: Booting VM...
==> oob-mgmt-server: Waiting for machine to boot. This may take a few minutes...
    oob-mgmt-server: SSH address: 127.0.0.1:2222
    oob-mgmt-server: SSH username: vagrant
    oob-mgmt-server: SSH auth method: private key

Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.

**Comment by ericpulvino** [comment]
Can you provide output from "vagrant --version"? 
We need to be running Vagrant v1.8.4.

**Comment by ericpulvino** [comment]
[Closing due to no response.]
