### ISSUE TITLE
Exit01/02 to Spine 01/02 ports are wrong

### ISSUE THREAD

**Issue by plumbis** [CumulusNetworks/cldemo-vagrant#17]
The .dot file (and actual cabling) don't match the topology diagram.

`"exit01":"swp51" -- "spine01":"swp30"
 "exit01":"swp52" -- "spine02":"swp30"
 "exit02":"swp51" -- "spine01":"swp29"
 "exit02":"swp52" -- "spine02":"swp29"`

Changing the topo diagram means inconsistent cabling.
Changing the cabling (and .dot file) could potentially break anything that relies on reference topo. 

I vote for the later with us validating that we don't break existing demos.

**Comment by isharacomix** [comment]
I believe the diagram is wrong. The idea was to count forward for regular leaves, and count backward from exit leaves to meet in the middle.

**Comment by ericpulvino** [comment]
Move to close this if all parties are satisfied.

**Comment by ericpulvino** [comment]
No comments in a month so I'm closing this issue.
