### ISSUE TITLE
remove ansible from requirements for vanilla cldemo-vagrant (vagrant up)

### ISSUE THREAD

**Issue by seanx820** [CumulusNetworks/cldemo-vagrant#2]
Windows users don't have an ability to use ansible (AFAIK) would be great to not have that requirement.  When I built up cl-bc-troubleshooting that requirement was not there.  Ideally Ansible only runs on oob-mgmt-server itself.

**Comment by isharacomix** [comment]
Running ansible on the oob mgmt server on itself is a decent idea. The flow would be like this:

    vagrant: install ansible
    vagrant: git clone separate repo
    vagrant: kick off ansible-playbook from inside oob-mgmt-server

The most important part is making sure the extra variables about the topology make it into the ansible playbook run.

**Comment by seanx820** [comment]
what are the "extra variables"

**Comment by isharacomix** [comment]
https://github.com/CumulusNetworks/cldemo-vagrant/blob/master/Vagrantfile#L308-L595

    device.vm.provision "ansible" do |ansible|
              ansible.playbook = "./playbook/site.yml"
              ansible.extra_vars = {wbench_hosts: {
                      exit02: {ip: "192.168.0.42", mac: "A0:00:00:00:00:42"},
                      exit01: {ip: "192.168.0.41", mac: "A0:00:00:00:00:41"},
                      spine02: {ip: "192.168.0.22", mac: "A0:00:00:00:00:22"},
                      spine01: {ip: "192.168.0.21", mac: "A0:00:00:00:00:21"},
                      leaf04: {ip: "192.168.0.14", mac: "A0:00:00:00:00:14"},
                      leaf02: {ip: "192.168.0.12", mac: "A0:00:00:00:00:12"},
                      leaf03: {ip: "192.168.0.13", mac: "A0:00:00:00:00:13"},
                      leaf01: {ip: "192.168.0.11", mac: "A0:00:00:00:00:11"},
                      edge01: {ip: "192.168.0.51", mac: "A0:00:00:00:00:51"},
                      server01: {ip: "192.168.0.31", mac: "A0:00:00:00:00:31"},
                      server03: {ip: "192.168.0.33", mac: "A0:00:00:00:00:33"},
                      server02: {ip: "192.168.0.32", mac: "A0:00:00:00:00:32"},
                      server04: {ip: "192.168.0.34", mac: "A0:00:00:00:00:34"},
                                  }}
    end

You need to pass the mac address mapping for the oob dhcp server to do its thing.
