### ISSUE TITLE
Pin Ansible Version

### ISSUE THREAD

**Issue by plumbis** [CumulusNetworks/cldemo-vagrant#20]
Currently the latest ansible version is pulled. No problems have been seen yet, but this could create regression issues unless we know the version of ansible won't break demos. 

We should pin the ansible version that is pulled on the oob-mgmt-server

**Comment by ddutt** [comment]
I already ran into an example of this. Variables such as "ansible_interfaces" MUST be within "{{ }}" in 2.2. They're silently ignored otherwise. In 2.1, you only get a "this is going to be deprecated" warning.

**Comment by ericpulvino** [comment]
Going to tackle this in the move to the "-c" workflow.

**Comment by ericpulvino** [comment]
Done. Pinned to 2.3.1.0 at this time.
