### ISSUE TITLE
VX nodes don't get IP addr with eth0 and kvm

### ISSUE THREAD

**Issue by ddutt** [CumulusNetworks/cldemo-vagrant#22]
Using KVM, leaf/spine/edge/internet nodes are not accessible from oob-mgmt-server. Since the vagrant interface has been killed as well, the boxes are unreachable except via console. 

On logging into the console, I notice that there's a dhclient running with eth0, but there's no IP address on eth0, but eth0 is up.

Virtualbox doesn't have this problem with version 5.1. I had a version 5.0.xx (not the one you recommend), and that had the same problem.

**Comment by ericpulvino** [comment]
Have not seen much of this issue lately. Will continue to monitor.

**Comment by ericpulvino** [comment]
The only time I see this now is when the DHCP process fails on the OOB-server.
