### ISSUE TITLE
Correct server lldp config

### ISSUE THREAD

**Issue by plumbis** [CumulusNetworks/cldemo-vagrant#27]
Default server lldp config is to send the MAC instead of the interface name in LLDP messages. 

As part of the setup, please create /etc/lldpd.d/port_info.conf

Inside the file place
configure lldp portidsubtype ifname

Restart lldpd.

**Comment by ericpulvino** [comment]
Going to tackle this in the move to the "-c" workflow.

**Comment by ericpulvino** [comment]
Added to TC here --> https://github.com/CumulusNetworks/topology_converter/commit/8dc207c53848c320340fa7c1b1f2099535dbdf0d will be picked-up soon in cldemo-vagrant.

**Comment by ericpulvino** [comment]
Done.
