### ISSUE TITLE
Feature Request: vagrant up always starts oob-mgmt-server first

### ISSUE THREAD

**Issue by seanx820** [CumulusNetworks/cldemo-vagrant#3]
David Ahern <dsa@cumulusnetworks.com> said when he did vagrant up the machines would boot faster than DHCP could pass out (oob-mgmt-server must not have booted yet).  I imagine he is using KVM?  Is there a way we always make oob-mgmt-server and oob-mgmt-switch boot first?

**Comment by isharacomix** [comment]
In virtualbox, oob-mgmt-server should always be booting first because it boots in the order they are specified in the template.

Not sure about kvm. I think it's possible to set a boot order, but I don't remember. @ericpulvino ?

**Comment by ericpulvino** [comment]
You would need to do the --no-parallel option in KVM to enforce boot order.... I think in that case it would go top-to-bottom as it parses the vagrantfile (just like virtualbox) but I need to test that theory.

**Comment by ericpulvino** [comment]
Yes. Use the --no-parallel option to start the libvirt topology in vagranttfile (top to bottom) order.
