### ISSUE TITLE
Investigate Removing Requirement for Vagrant-Cumulus Plugin

### ISSUE THREAD

**Issue by ericpulvino** [CumulusNetworks/cldemo-vagrant#30]
To get away from recent changes in vagrant. It does not appear to be needed for how we use vagrant with the cldemo infrastructure. Need to investigate further.

**Comment by seanx820** [comment]
@ericpulvino I got rid of this requirement for cldemo-evpn, it seems to work fine.

- remove hostname Vagrant config for any devices that are running CumulusVX
- make sure hostnames are set via DHCP (from oob-mgmt-server)
- remove vagrant config requiring vagrant-cumulus plugin

**Comment by ericpulvino** [comment]
Removed as part of https://github.com/CumulusNetworks/topology_converter/pull/47 in TC. Sounds like Barry might get to it first in Cldemo-vagrant. Reassigning to him.

**Comment by ericpulvino** [comment]
Done.
