### ISSUE TITLE
Please change MAC address on Ubuntu servers

### ISSUE THREAD

**Issue by Diane-cumulus** [CumulusNetworks/cldemo-vagrant#31]
Can you change topo converter to have a MAC address of a common NIC run on the Ubuntu servers or some random number?  We could also match the mac address up with the server number and interface if at all possible to make reading them easy.

For example (I know I am using Decnet addresses, but meant as example only, don't use this!!!)
server01 eth1 may be something like this (just an example):  AA 00 04 01 01 00
server01 eth 2 may be something like this (example again):  AA 00 04 01 02 00
Server 02 eth1:  AA 00 04  02 01 00
server02 eth2  AA 00 04 02 02 00

etc.

Today, the mac addresses assigned are Cumulus Linux, which can be confusing especially for features like EVPN.  For example:

*** System restart required ***
----------------------------------------------------------------
  Ubuntu 16.04 LTS                            built 2016-04-26
----------------------------------------------------------------
Last login: Thu Jan  5 15:24:16 2017 from 192.168.0.254
vagrant@server03:~$ ip link show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: vagrant: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 08:00:27:ce:ef:c8 brd ff:ff:ff:ff:ff:ff
3: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
    link/ether a0:00:00:00:00:33 brd ff:ff:ff:ff:ff:ff
4: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
    link/ether **44:38:39:00:00:28** brd ff:ff:ff:ff:ff:ff
5: eth2: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether **44:38:39:00:00:65** brd ff:ff:ff:ff:ff:ff
v

**Comment by ericpulvino** [comment]
Team has agreed on this mapping. Implementation to come.
 "server01":"eth1" -- "leaf01":"swp1" [left_mac="00:03:00:11:11:01"]
 "server01":"eth2" -- "leaf02":"swp1" [left_mac="00:03:00:11:11:02"]
 "server02":"eth1" -- "leaf01":"swp2" [left_mac="00:03:00:22:22:01"]
 "server02":"eth2" -- "leaf02":"swp2" [left_mac="00:03:00:22:22:02"]
 "server03":"eth1" -- "leaf03":"swp1" [left_mac="00:03:00:33:33:01"]
 "server03":"eth2" -- "leaf04":"swp1" [left_mac="00:03:00:33:33:02"]
 "server04":"eth1" -- "leaf03":"swp2" [left_mac="00:03:00:44:44:01"]
 "server04":"eth2" -- "leaf04":"swp2" [left_mac="00:03:00:44:44:02"]

**Comment by ericpulvino** [comment]
Pushed fix to master.
