### ISSUE TITLE
add config.vbguest.auto_update = false to Vagrantfile

### ISSUE THREAD

**Issue by akhomyakov** [CumulusNetworks/cldemo-vagrant#32]
Please, add config.vbguest.auto_update = false to Vagrantfile, otherwise it tries to update GuestAdditions for vbox on every node, which not only fails on CumulusVX, but also takes forever on the Ubuntu VMs

**Comment by ericpulvino** [comment]
Thanks Andrey; will address this in my next development session!

**Comment by akhomyakov** [comment]
I tried to add it in my lab and it prevents oob-mgmt-server from coming up. I haven't figured out why that is yet, but that is literally the only change and it has this effect on the provisioning.
It's erring out with `==> oob-mgmt-server: E
==> oob-mgmt-server: :
==> oob-mgmt-server: Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/m/markupsafe/python-markupsafe_0.23-2build2_amd64.deb  Hash Sum mismatch
==> oob-mgmt-server: E
==> oob-mgmt-server: :
==> oob-mgmt-server: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
`

**Comment by ericpulvino** [comment]
Tried to recreate this but I have not run into this issue. I see it complains that the guest additions are old but I see no attempts to update them.

**Comment by ericpulvino** [comment]
@akhomyakov Are you still having this issue? I've yet to be able to recreate the update of guest additions in any of the simulations I've seen.

**Comment by akhomyakov** [comment]
To be honest, I'm not sure. I haven't use the demo in a while. My homemade Vagrantfile does have config.vbguest.auto_update = false.

**Comment by ericpulvino** [comment]
I appreciate your honesty. As a thank you I will help you rack your next fridge.
