### ISSUE TITLE
ttyname failed and Inappropriate ioctl for device

### ISSUE THREAD

**Issue by akhomyakov** [CumulusNetworks/cldemo-vagrant#33]
While there is a "fix" for this message in the script and it does output "Ignore the previous error, fixing this now..." to the tty, it's in the least, unsightly.
I suggest running something like this before any shell commands are executed on the vm.

device.vm.provision :shell , inline: "sudo sed -i '/tty/!s/mesg n/tty -s \\&\\& mesg n/' /root/.profile && echo 'Fixing Inappropriate ioctl for device error message'" , privileged: false

**Comment by ericpulvino** [comment]
As I recall from my previous experience with this error it is unavoidable at least once. As a matter of fact, the first shell action we call is to fix the issue (see: https://github.com/CumulusNetworks/cldemo-vagrant/blob/master/Vagrantfile#L441-L442 ) actually the instantiation of the shell to fix the error message is what causes the first (and only) instance of the message.

**Comment by akhomyakov** [comment]
Fixing it with "privileged: false" as I provided doesn't result in error while fixing it. In other words, the error you are fixing here only manifests itself if you execute the command a root, but doesn't if you sudo with "privileged: false" flag.
