### ISSUE TITLE
Vagranfile.j2 template out of sync with topology_converter

### ISSUE THREAD

**Issue by mbrownatcumulus** [CumulusNetworks/cldemo-vagrant#37]
I tried generating a new Vagrantfile using the instructions in the readme, but the resulting vagrantfile was full of errors.  I then downloaded the latest Vagrantfile.j2 template from topology_converter to my local templates dir.  The resulting Vagrantfile worked.
The README needs to be updated to also included downloading the latest Vagrantfile.j2 template from the topology_converter repo.

**Comment by ericpulvino** [comment]
I am all to painfully aware of this issue. Cldemo-vagrant is 6+ months out of date... master is built on 3.2.0. This branch will be pushed to master soon and addresses your concern --> https://github.com/CumulusNetworks/cldemo-vagrant/tree/tc_dash_c

**Comment by ericpulvino** [comment]
Fixed.
