### ISSUE TITLE
Unable to deploy Cumulux VX image on VirtuallBox using provided instructions

### ISSUE THREAD

**Issue by jamesfreeman959** [CumulusNetworks/cldemo-vagrant#38]
Hi there,

I have been attempting to deploy the cldemo on VirtualBox using vagrant, but when it comes to the stage of setting up the Cumulus VX images, I get the following message:

```
==> oob-mgmt-switch: Box 'CumulusCommunity/cumulus-vx' could not be found. Attempting to find and install...
    oob-mgmt-switch: Box Provider: virtualbox
    oob-mgmt-switch: Box Version: 3.2.0
The box 'CumulusCommunity/cumulus-vx' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/CumulusCommunity/cumulus-vx"]
Error: The requested URL returned error: 404 Not Found
```
I note that Vagrant images are being migrated away from hashicorp to vagrantup.com - however right now the Cumulux VX image doesn't seem to work - if I navigate manually to this page, I get a 404 error:

https://app.vagrantup.com/CumulusCommunity/boxes/cumulus-vx

I tried manually downloading the Cumulus VX box image and performing a vagrant box add, but I then get this error:

```
==> oob-mgmt-switch: Checking if box 'CumulusCommunity/cumulus-vx' is up to date...
The box 'CumulusCommunity/cumulus-vx' is not a versioned box. The box was added
directly instead of from a box catalog. Vagrant can only
check the versions of boxes that were added from a catalog
such as from the public Vagrant Server.
```

Is this a transient error caused by the migration to vagrantup.com, or is there a code change required?

Kind regards,

James

**Comment by ericpulvino** [comment]
Thanks for reporting, investigating....

**Comment by ericpulvino** [comment]
I'm seeing the same error on https://app.vagrantup.com/CumulusCommunity/boxes/cumulus-vx ... I'm guessing this might have something to do with Vagrant's cut-over to the new hosting service as they were working yesterday. Will keep this updated as I learn more.

**Comment by ericpulvino** [comment]
Confirmed, this is an artifact of the Vagrant Cloud migration. The case I opened with Hashicorp has been resolved and access should be back to normal. Please confirm if otherwise.
