### ISSUE TITLE
Bring back kvm wbid

### ISSUE THREAD

**Issue by plumbis** [CumulusNetworks/cldemo-vagrant#40]
I understand I can use TC to build a new vagrantfile if I need custom port ranges for this, but that is a PITA. Having the wbid there made it very easy to customize the port range without having to jump through the hoops of TC.

**Comment by ericpulvino** [comment]
We have since solved this with the introduction of the -i option in the upcoming version of TC 4.7.0

```
  -i TUNNEL_IP, --tunnel-ip TUNNEL_IP
                        FOR LIBVIRT PROVIDER: this option overrides the
                        tunnel_ip setting for all nodes. This option provides
                        another method of udp port control in that all ports
                        are bound to the specified ip address.
```

Closing this.
