### ISSUE TITLE
Exit01/02 to Spine 01/02 ports actual cabling and diagram disagree

### ISSUE THREAD

**Issue by jcross-linkup** [CumulusNetworks/cldemo-vagrant#41]
This is the same problem as reported in issue #17.  It doesn't look like any fix was ever made.  This tripped me up for a while today while trying to learn Cumulus on my laptop before deploying our hardware switches.

From comments on #17, it sounds like the cldemo_topology.png diagram should be changed to match the topology.dot file.

**Comment by ericpulvino** [comment]
Thanks for pointing this out. I'll fix this immediately.

**Comment by ericpulvino** [comment]
Pushed to all relevant branches for 3.x+. Thanks again for pointing this out.
