### ISSUE TITLE
use extended ping in cumulus ? how ? is it available ? 

### ISSUE THREAD

**Issue by yusufq8** [CumulusNetworks/cldemo-vagrant#45]
how to use extended ping in cumulus like with repeat 100 , tos 184 , source int or source ip etc

**Comment by ericpulvino** [comment]
Extended ping is a Cisco term. To use the parameters you specified in Linux use the following syntax 

`ping -c 100 -Q 184 -I vlan10 8.8.8.8`

See the MAN page for the ping utility by running `man ping` or a short list with `ping -h`
