### ISSUE TITLE
Future deprecation in favor of cldemo2

### ISSUE THREAD

**Issue by nqb** [CumulusNetworks/cldemo-vagrant#53]
Hello,

I would like to know if this repo will be deprecated in favor of https://gitlab.com/cumulus-consulting/goldenturtle/cldemo2 ?

**Comment by plumbis** [comment]
Yes, we will be deprecating this as well as the rest of the cldemo-* examples. I would suggest using the golden turtle cldemo2 for anything you're planning on testing.

We do not plan on removing them from github in the near future so this will remain for reference but will no longer be updated.

**Comment by nqb** [comment]
Hi @plumbis,

Thanks for your answer, see you around cldemo2 ;-)
